apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/react-app

commonLabels:
  app: react-app
  database: enabled
  tier: frontend

patches:
- path: deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: react-app
    version: v1
- path: virtual-service-patch.yaml
  target:
    group: networking.istio.io
    kind: VirtualService
    name: vs-react-app
    version: v1beta1

images:
- name: react-app
  newName: hhttp://asia-southeast2-docker.pkg.dev/devops-412909/logique-registry/app-reactjs
  newTag: main

namespace: prd-logique
