apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/node-app

commonLabels:
  app: node-app
  database: enabled
  tier: backend

patches:
- path: deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: node-app
    version: v1
- path: virtual-service-patch.yaml
  target:
    group: networking.istio.io
    kind: VirtualService
    name: vs-node-app
    version: v1beta1

images:
- name: node-app
  newName: http://asia-southeast2-docker.pkg.dev/devops-412909/logique-registry/app-nodejs
  newTag: main

namespace: prd-logique
